Split rank update embed into multiple embeds.
cheran-senthil/TLE pull request #327
Opened 2020-05-29 00:40 UTC by aryanc403

Fixes #302

2020-05-30 16:21 UTC, algmyr commented on tle/util/discord_common.py
> +    return discord.Embed(**kwargs, color=_CF_COLORS[int(len(_CF_COLORS)*seed/100)])
This solution feels awkward. What about modifying and refactoring `cf_color_embed` instead?

E.g.
* factor out the `random.choice(_CF_COLORS)` into `random_cf_color()`
* make the signature `def cf_color_embed(*, color=None, **kwargs):`
* add line `color = color or random_cf_color()`, add `color=color` in embed.

2020-05-30 16:23 UTC, algmyr commented on tle/cogs/handles.py
> +            rank_changes_str=['No rank changes']
Could be written with a one-liner with `or`

2020-05-30 16:23 UTC, algmyr commented on tle/cogs/handles.py
> +        embed_color_seed=random.randrange(0,100)
Reconsider this approach, see notes in cf_common

2020-05-30 16:28 UTC, algmyr commented on tle/cogs/handles.py
> +                embed.set_author(name='Rank updates')
Can fields be set afterwards in general? If so consider generating the more generic version (simpler and more obvious code in the loop) and set the relevant stuff for embed[0] afterwards. This also removes the need for the awkward usage of `start`.

2020-05-30 16:29 UTC, algmyr commented on tle/cogs/handles.py
> +            desc = '\n'.join(rank_changes_str[start:start+_MAX_RATING_CHANGES_PER_EMBED])
Use `paginator.chunkify` to make this readable. The changes suggested below would remove the need to have start to recognize the first iteration and should make things cleaner in general.

This might simplify to the degree that you could use a list comprehension.

2020-07-23 13:47 UTC, krofna commented on tle/cogs/handles.py
> +_MAX_RATING_CHANGES_PER_EMBED = 20
Are you sure 20 definitely fit? i've never seen more than 16

2020-08-02 05:41 UTC, aryanc403 commented
Ready for review.

2020-08-29 11:58 UTC, aryanc403 commented
@meooow25 Updated the requested change.

2020-08-29 20:57 UTC, meooow25 requested changes

2020-08-29 20:57 UTC, meooow25 commented on tle/cogs/handles.py
> +                    embeds = self._make_rankup_embed(guild, contest, change_by_handle)
Rename to `_make_rankup_embeds`.

2020-08-29 20:57 UTC, meooow25 commented on tle/cogs/handles.py
> +            title=contest.name, url=contest.url, description="")
There is no point in calling `cf_color_embed` when the color is changed later anyway. You can simply use `discord.Embed`.
Same below.

2020-08-29 20:57 UTC, meooow25 commented on tle/util/discord_common.py
> +    return embeds
No need to return these since the input embeds are mutated.

2020-08-30 01:35 UTC, aryanc403 commented
Updated.

2020-08-30 08:41 UTC, meooow25 approved these changes

2020-08-30 08:41 UTC, meooow25 commented on tle/util/discord_common.py
> +def cf_same_color_embeds(embeds):
Maybe rename to `set_same_cf_color`.

2020-08-30 08:41 UTC, meooow25 commented on tle/cogs/handles.py
> +_TOP_DELTAS_COUNT = 10
Sneaky 😏

2020-08-31 20:49 UTC, merged