Updated to Discord 1.5.0
cheran-senthil/TLE pull request #409
Opened 2020-11-07 00:38 UTC by dgcnz

These are the changes that were referred in #408. I've tested it so far with a few commands and it seems to be working, but it is far from an exhaustive test.

2020-11-08 07:04 UTC, algmyr requested changes

2020-11-08 07:04 UTC, algmyr commented on tle/__main__.py
> +    intents = discord.Intents.all()
Should we do `all()` or something more specific? Seems like `all()` is currently default + presences and members. We could specify that explicitly so we don't pull in extra stuff in the future. If I read the docs correctly it would be
```
intents = discord.Intents.default()
intents.presences = True
intents.members = True
```
Would be good to have opinions on other devs on this @meooow25 @krofna

2020-11-08 17:39 UTC, meooow25 commented on tle/__main__.py
> +    intents = discord.Intents.all()
I don't think we need presence, just members would do.
Also ideally we could change the code to not depend on cached members, but that would need some digging and this is good enough to fix the issue a lot of people seem to be having, so I'm okay with it.

2020-11-09 13:32 UTC, dgcnz commented on tle/__main__.py
> +    intents = discord.Intents.all()
Added Intents.default() + members, seems to be working fine.

2020-11-10 14:24 UTC, meooow25 approved these changes

2020-11-10 15:36 UTC, algmyr approved these changes

2020-11-10 15:37 UTC, merged

2020-11-10 15:37 UTC, algmyr commented
Thanks!