Issue/324
cheran-senthil/TLE pull request #410
Opened 2020-11-12 21:08 UTC by dgcnz

I'm filtering the contests described in issue #324 (and 1431, 1432) only at `update_task` and `monitor_task` so that one can still query for them. 

For now it's basically a global list `CONTEST_BLACKLIST` with the banned contest_ids, but I think we could also automate it.

As far as I could tell there are 3 kinds of "unrated" contests based on their result on [contest.ratingChanges](https://codeforces.com/api/contest.ratingChanges?contestId=contestid): 

1. Normal CF contests that were unrated: `{"status":"OK","result":[]}`
2. Non-CF contests that should not be monitored (this was the case in the aforementioned banned contests but maybe there are false-positives): `{"status":"FAILED","comment":"contestId: Rating changes are unavailable for this contest"}` 
3. Normal CF contests that haven't finished yet (I tested this with contest 1438, so this might also not be the case in actual running contests): `{"status":"FAILED","comment":"contestId: Rating changes are unavailable, because the contest isn\u0027t finished yet"}`

The code in `ratingChanges` at `codeforces_api.py:282` deals with errors in this way:
```python
        except TrueApiError as e:
            if 'not found' in e.comment:
                raise ContestNotFoundError(e.comment, contest_id)
            if 'Rating changes are unavailable' in e.comment:
                raise RatingChangesUnavailableError(e.comment, contest_id)
            raise
```

We could maybe add another if-clause there to deal specifically with the banned contests instead of manually adding them on the code (I'm fairly new to TLE's code so I didn't dare to touch more code haha). 

Nonetheless, the current change should work in the meantime.

2020-11-14 06:19 UTC, aryanc403 commented
https://discordapp.com/invite/2CJ6qvY

2020-11-14 14:47 UTC, dgcnz commented
Thanks, I just joined :)

2020-11-14 17:00 UTC, algmyr requested changes

2020-11-14 17:00 UTC, algmyr commented on tle/util/cache_system2.py
> +        check = lambda contest : self.is_newly_finished_without_rating_changes(contest) and contest.id not in CONTEST_BLACKLIST
Again, inline check.

2020-11-16 22:40 UTC, algmyr requested changes

2020-11-16 22:40 UTC, algmyr commented on tle/util/cache_system2.py
> +                                   not _is_blacklisted(contest.id)]
```suggestion
        self.monitored_contests = [
            contest for contest in self.monitored_contests
            if self.is_newly_finished_without_rating_changes(contest)
            and not _is_blacklisted(contest.id)
        ]
```

2020-11-16 22:40 UTC, algmyr commented on tle/util/cache_system2.py
> +                      not _is_blacklisted(contest.id)]
```suggestion
        to_monitor = [
            contest for contest in
            self.cache_master.contest_cache.contests_by_phase['FINISHED']
            if self.is_newly_finished_without_rating_changes(contest)
            and not _is_blacklisted(contest.id)
        ]
```

2020-11-17 07:43 UTC, algmyr approved these changes
LGTM now :)

2020-11-17 07:43 UTC, merged