Improve logging output
cheran-senthil/TLE pull request #436
Opened 2021-01-18 20:27 UTC by PotatoHashing

This change

- Wraps logging output in a code block to prevent discord formatting on tracebacks.
- Adds embed for link and command that caused an exception.
- Remove logging from ;cache command because it double logged to channel where the command was sent, and in logging channel.
- Remove code block formatting from logging start up.

Fixes #404 

**Before**:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/8847876/104960073-6e60c180-59cb-11eb-8a6d-a4ee29adf1d3.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/8847876/104956496-238f7b80-59c4-11eb-88f5-4f4e0b283c5f.png">
**After**:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/8847876/104959910-2477db80-59cb-11eb-86c6-d6533b2f8c0b.png">
<img width="985" alt="image" src="https://user-images.githubusercontent.com/8847876/104957117-7289e080-59c5-11eb-8456-339ca3a2b717.png">

2021-01-23 13:43 UTC, meooow25 commented on tle/cogs/cache_control.py
> +        pass
Can delete the function.

2021-01-23 13:43 UTC, meooow25 commented on tle/cogs/logging.py
> +                    await channel.send('`Check logs for full stack trace`')
Thanks, this should have been here from the beginning.

2021-01-23 13:43 UTC, meooow25 commented on tle/cogs/logging.py
> +                    pass
What is this for? 🤔

2021-01-23 13:43 UTC, meooow25 commented on tle/cogs/logging.py
> +                        embed=discord_common.embed_failed_command(record))
I would prefer it be a simple message, embeds take up a lot of space and looks don't matter in the logging channel.

2021-02-08 08:21 UTC, PotatoHashing commented on tle/cogs/cache_control.py
> +        pass
Done.

2021-02-08 08:21 UTC, PotatoHashing commented on tle/cogs/logging.py
> +                    await channel.send('`Check logs for full stack trace`')
Acknowledged.

2021-02-08 08:21 UTC, PotatoHashing commented on tle/cogs/logging.py
> +                    pass
Added comment. Some records don't have the jump url and will throw the AttributeError.
I think it's exceptions not thrown from tle/util/discord_common.py#83

Apparently it's pythonic to ask for forgiveness instead of permission?
https://stackoverflow.com/a/610923

2021-02-08 08:21 UTC, PotatoHashing commented on tle/cogs/logging.py
> +                        embed=discord_common.embed_failed_command(record))
:blobsad: changed.

2021-02-09 22:25 UTC, meooow25 commented on tle/cogs/logging.py
> +                    pass
Ah I see, was a bit hard to follow because the attr access was inside the `embed_failed_command` function.

2021-02-09 22:41 UTC, meooow25 requested changes

2021-02-09 22:41 UTC, meooow25 commented on tle/util/discord_common.py
> +        })
This formatting is super weird, can we rearrange things a bit? Any way you prefer so that it's nicer.

2021-02-09 22:41 UTC, meooow25 commented on tle/cogs/logging.py
> +                    channel.send('```Jump Url: {}```'.format(record.jump_url))
Not sure if all records will always have `message_content`. Error thrown which are caught by discord will, I think but any other place where an error is directly logged will not have it.
Also I think we could bundle this and jump url in the same message.
And missed `await` in the second send 👀

2021-02-09 22:41 UTC, meooow25 commented on tle/cogs/logging.py
> +            'Skipping installation of logging cog as logging channel is not provided.')
Could you maybe revert some of these modified lines?
Adding blank lines is fine but for other stuff algmyr has a separate PR anyway so that should take care of it.

2021-02-19 04:39 UTC, PotatoHashing commented
I don't have a dev TLE anymore so I won't be able to verify these changes.

2021-02-21 18:12 UTC, krofna commented
We can make the minor changes ourselves and merge it.

2021-03-01 00:29 UTC, PotatoHashing commented on tle/cogs/logging.py
> +            'Skipping installation of logging cog as logging channel is not provided.')
Reverted the non-adding-blank-line formatting changes.

2021-03-01 00:37 UTC, PotatoHashing commented on tle/cogs/logging.py
> +                    channel.send('```Jump Url: {}```'.format(record.jump_url))
For what I've seen, errors will just have `record.message_content` = `None` which still prints in the error message just fine. Missing jump_urls caused another error to be thrown though. I think any kind of command that doesn't exist should trigger this (such as `;fake_command`) but I haven't tested extensively. 

Merged both messages into the same message inside the await.

2021-03-01 00:37 UTC, PotatoHashing commented on tle/util/discord_common.py
> +        })
Done.

2021-03-02 17:39 UTC, meooow25 requested changes
Everything looks good, please resolve the jump url clickable thing and we can merge.

2021-03-02 17:39 UTC, meooow25 commented on tle/util/discord_common.py
> +        embed.color = color
Revert

2021-03-02 17:39 UTC, meooow25 commented on tle/util/discord_common.py
> +                waiter=tasks.Waiter.fixed_delay(5*60))
Revert

2021-03-02 17:39 UTC, meooow25 commented on tle/cogs/logging.py
> +                # Not all errors have jump urls.
Maybe update this comment to mention message_content since the handling for that is same as jump_url?

2021-03-02 17:39 UTC, meooow25 commented on tle/cogs/logging.py
> +                            record.message_content, record.jump_url))
okarinn reported that this makes the jump URL non-clickable.
Leaving out the backticks so its not a code block should fix that.

2021-03-02 17:39 UTC, meooow25 commented on tle/cogs/logging.py
> +                    channel.send('```Jump Url: {}```'.format(record.jump_url))
That's... weird. I checked and a message always has content and jump_url ([src](https://github.com/Rapptz/discord.py./blob/d01500bccd8dd87a96edb62b259856e9fa4c9ec6/discord/message.py#L338-L345)).  
Would be nice if you could look further into when that is happening, but not strictly required for this PR.

2021-03-02 18:14 UTC, PotatoHashing commented on tle/util/discord_common.py
> +        embed.color = color
Done.

2021-03-02 18:14 UTC, PotatoHashing commented on tle/util/discord_common.py
> +                waiter=tasks.Waiter.fixed_delay(5*60))
Done

2021-03-02 18:14 UTC, PotatoHashing commented on tle/cogs/logging.py
> +                # Not all errors have jump urls.
Done.

2021-03-02 18:15 UTC, PotatoHashing commented on tle/cogs/logging.py
> +                            record.message_content, record.jump_url))
Thanks okarinn for testing. Done.

2021-03-02 19:40 UTC, meooow25 approved these changes

2021-03-02 20:06 UTC, merged