Enhance Dockerfile to make container persistent and UPD Docker.md accordingly
cheran-senthil/TLE pull request #446
Opened 2021-02-19 13:27 UTC by Shahraaz

2021-02-19 18:55 UTC, algmyr requested changes
Also, general comment: I presume that the DBs will now be inside the actual image? Would it be useful to give some examples as to how to access/extract them if needed?

2021-02-19 18:55 UTC, algmyr commented on Docker.md
> +foo@bar:~$ sudo docker exec -it container_id bash
I think it's customary to mark the parts that you are supposed to replace, e.g. writing `<container_id>`

2021-02-19 18:55 UTC, algmyr commented on Dockerfile
Should the author script (`extra/scrape_cf_contest_writers.py`) also be ran here? It's a script that really should be run occasionally just to keep the author list somewhat fresh, so not sure where the best place for it would be.

2021-02-19 19:22 UTC, Shahraaz commented on Docker.md
> +foo@bar:~$ sudo docker exec -it container_id bash
ok, fixed

2021-02-19 19:28 UTC, Shahraaz commented on Dockerfile
It can be run, but it is better to run the script outside the container (as a normal user script). 

As long as the bot is mounted(i.e. run using `sudo docker run -v ${PWD}:/TLE -it --net host <image_id>`), the change will be reflected inside the bot as usual.

2021-02-19 19:36 UTC, Shahraaz commented
> Also, general comment: I presume that the DBs will now be inside the actual image? Would it be useful to give some examples as to how to access/extract them if needed?

As long as the bot is mounted(i.e. run using sudo docker run -v ${PWD}:/TLE -it --net host <image_id>), the change will be reflected inside the bot as usual. files will be available both inside the container and on your local machine. 

But if the user chooses to not mount the bot (not use -v ${PWD}:/TLE flag), I have already added instructions in [Docker.md](https://github.com/Shahraaz/TLE/blob/master/Docker.md#debuggingrunning-commands-inside-the-container)

![Screenshot from 2021-02-20 01-05-50](https://user-images.githubusercontent.com/29424947/108552818-d3d00700-7317-11eb-89b1-269e9cb4f44f.png)

2021-02-19 20:18 UTC, Shahraaz commented on Dockerfile
I tried running the command while building and it executed properly too. But the file is not written anywhere, it is neither present inside the container nor outside. Better to run the script separately.

2021-02-21 18:07 UTC, algmyr approved these changes

2021-02-21 18:07 UTC, merged