Codechef atcoder support
cheran-senthil/TLE pull request #470
Opened 2021-07-22 06:00 UTC by iampjeetsingh

Implemented the following `;handle identify`, `;handle set`, `;handle list`, `;ranklist` commands for CodeChef / AtCoder / Google (Kickstart)

2021-07-22 14:07 UTC, cheran-senthil commented
Don't think we want these for other sites, general consensus is against this.

2021-07-22 14:28 UTC, krofna commented
#94 for reference

2021-07-22 15:16 UTC, iampjeetsingh commented
Which features were you talking in #468 then?

2021-07-22 15:24 UTC, krofna commented
@iampjeetsingh just ignore what cheran said. this requires detailed discussion. please provide your discord username so that we can invite you to the development server

2021-07-22 15:34 UTC, iampjeetsingh commented
My discord username is thesupremeone#1162

2021-08-22 13:21 UTC, algmyr requested changes

2021-08-22 13:21 UTC, algmyr commented on tle/util/clist_common.py
> +    return ranklist
A lot of these functions are on the form
```
if cf: minor logic + dispatch to cf_common

do complex clist logic
```
It might make sense to have a some overarching util (maybe `resource_util` for lack of better words) that does the backend agnostic work+the minor logic in the pseudocode above, and dispatches to cf_util or clist_util for specific implementations of e.g. ranklist. I.e. that ranklist functions does minor logic followed by dispatch to the specific impl of ranklist.

I suppose the resource code should also move there, just leaving the clist impl details here.

2021-08-22 13:21 UTC, algmyr commented on tle/util/db/user_db_conn.py
>  from discord.ext import commands
@meooow25 or @narutse, could you look at the db related code?

2021-08-22 13:21 UTC, algmyr commented on tle/util/scaper.py
> +import requests
Might want to make this use aiohttp like the rest of the code which makes the request async.

2021-08-22 13:21 UTC, algmyr commented on tle/util/scaper.py
> +from bs4 import BeautifulSoup
File comment:
If the core clist identify logic gets moved to clist_common this scraper code could be moved there.

2021-08-22 22:05 UTC, narutse commented on tle/util/clist_api.py
> +class Contest(CfContest):
I think having Contest subclass CfContest to change one field is a bit weird. Should probably put this in a common class.

2026-02-16 10:43 UTC, closed without merging