Added ;plot progress
cheran-senthil/TLE pull request #482
Opened 2021-12-31 00:34 UTC by ashwinbanwari

Hello, this creates a new way to plot. It is similar to ;plot rating except the x-axis is contest number for that user (i.e. if a user compete in 10 contests, x-axis is from 1-10), thus evenly spacing out contests for them on the graph. For multi-user, the user with less contests has their graph cut off at contest x where x is that user's last contest. This provides an interesting way to compare users. 
![image](https://user-images.githubusercontent.com/52060395/147796435-54db0616-45ae-4d83-9948-021bbd1e4005.png)

2022-01-03 19:17 UTC, krofna commented
@algmyr what do you think? should this just be a flag for plot rating or this is good?

2022-01-03 19:27 UTC, algmyr commented
> @algmyr what do you think? should this just be a flag for plot rating or this is good?

Considering the logic in the command function is pretty much identical it probably makes more sense as a flag.

2022-01-04 00:52 UTC, ashwinbanwari commented
> > @algmyr what do you think? should this just be a flag for plot rating or this is good?
> 
> 
> 
> Considering the logic in the command function is pretty much identical it probably makes more sense as a flag.

I can change this to a flag. I noticed while testing, putting the legend in the bottom right was much better on average than putting it in top left (since rating graphs are often more like logarithmic curve than linear), can I change the plot in general to make it bottom right legend or should I do it just for this flag (where this problem is more severe)

2022-01-04 02:13 UTC, algmyr requested changes

2022-01-04 02:13 UTC, algmyr commented on tle/cogs/graphs.py
> +def _plot_progress(resp, mark='o'):
I would prefer some deduplication of logic here. E.g. we can have something like
```
def _plot_rating(plot_data, mark):
    for when, ratings in plot_data:
        plt.plot(when,
                 ratings,
                 linestyle='-',
                 marker=mark,
                 markersize=3,
                 markerfacecolor='white',
                 markeredgewidth=0.5)
    gc.plot_rating_bg(cf.RATED_RANKS)

def _plot_rating_by_date(resp, mark='o'):
    def gen_plot_data():
        for rating_changes in resp:
            ratings, times = [], []
            for rating_change in rating_changes:
                ratings.append(rating_change.newRating)
                times.append(dt.datetime.fromtimestamp(rating_change.ratingUpdateTimeSeconds))
            yield (rating, times)

    _plot_rating(gen_plot_data(), mark)
    plt.gcf().autofmt_xdate()

def _plot_rating_by_contest(...):
    ... similar to above, minus the date formatting line
```
which factors out the common plot formatting.

2022-01-04 02:13 UTC, algmyr commented on tle/cogs/graphs.py
> +    @plot.command(brief='Plot Codeforces rating graph by contests', usage='[+zoom] [+peak] [handles...] [d>=[[dd]mm]yyyy] [d<[[dd]mm]yyyy]')
As discussed, considering almost all logic is the same, make this a flag for the rating command instead.

2022-01-04 02:24 UTC, algmyr commented
> I noticed while testing, putting the legend in the bottom right was much better on average than putting it in top left (since rating graphs are often more like logarithmic curve than linear), can I change the plot in general to make it bottom right legend or should I do it just for this flag (where this problem is more severe)

Getting the positioning correct is not easy. Bottom-right will mess up the plot for people who have a big rating dip or who converge to a rating lower than the starting one. Top-left was chosen because it mostly only messes up for people who never exceed their starting rating. It's not perfect, but it tended to be better behaved than letting matplotlib pick the legend position.

I would expect curves to often be similar between the date and num_contest plots, so it probably makes sense to have the same behavior for both. I would vote top-left for both, but @meooow25 @krofna please chime in.

2022-01-04 04:30 UTC, ashwinbanwari commented
> > I noticed while testing, putting the legend in the bottom right was much better on average than putting it in top left (since rating graphs are often more like logarithmic curve than linear), can I change the plot in general to make it bottom right legend or should I do it just for this flag (where this problem is more severe)
> 
> 
> 
> Getting the positioning correct is not easy. Bottom-right will mess up the plot for people who have a big rating dip or who converge to a rating lower than the starting one. Top-left was chosen because it mostly only messes up for people who never exceed their starting rating. It's not perfect, but it tended to be better behaved than letting matplotlib pick the legend position.
> 
> 
> 
> I would expect curves to often be similar between the date and num_contest plots, so it probably makes sense to have the same behavior for both. I would vote top-left for both, but @meooow25 @krofna please chime in.

hmm I think I may not have observed bottom right messing up that much because of the change that everyone starts with 0 rating (and few ever stay around there), but I can see how that could be problem of older users rating graphs. Anyway, I'll wait for other opinions.

2022-01-06 08:08 UTC, ashwinbanwari commented
For now, I made it a flag (left the legend stuff untouched). maybe we can get this merged in the mean time? @algmyr

2022-01-06 18:51 UTC, algmyr approved these changes
LGTM

2022-01-06 18:51 UTC, merged