Add support for +official flag in ranklist
cheran-senthil/TLE pull request #509
Opened 2023-04-30 14:28 UTC by prabh1601

1. Ranklist can now show official participants in ranklist
2. Ranklist will fallback to predicted rating changes if fetched rating changes are not available
3. Remove predicted rating changes for events with "icpc" in name (these represent icpc mirrors or optimization contests)
4. Minor refactorings

2023-04-30 14:31 UTC, prabh1601 commented
Possibly solves #72 and #244

2023-04-30 22:23 UTC, algmyr requested changes

2023-04-30 22:23 UTC, algmyr commented on tle/util/cache_system2.py
> +        if not show_unofficial and 'Educational' in ranklist.contest.name:
This shouldn't be `and`, should it?

2023-04-30 22:23 UTC, algmyr commented on tle/util/ranklist/ranklist.py
> +    def fix_rated_standings(self):
Make this more descriptive. Something with `remove_unofficial` would make sense

2023-04-30 22:23 UTC, algmyr commented on tle/util/ranklist/ranklist.py
> +            id_ = row.party.teamName or row.party.members[0].handle
What's the rationale for this change in logic?

2023-04-30 22:23 UTC, algmyr commented on tle/util/ranklist/ranklist.py
> +        last_rated_rank, last_rated_score = 0, (-1, -1)
Split this into two assignments.

2023-04-30 22:23 UTC, algmyr commented on tle/util/ranklist/ranklist.py
> +        fixed_standings = []
with name change above, maybe this should be `official_standings`

2023-04-30 22:23 UTC, algmyr commented on tle/util/ranklist/ranklist.py
> +            handle = contestant.party.teamName or contestant.party.members[0].handle
It seems this logic is repeated a bunch, maybe it should be broken out into a function?

2023-05-01 18:07 UTC, prabh1601 commented on tle/cogs/contests.py
> +                                                                               show_unofficial=show_official is False)
Oh yes, this is good.

2023-05-01 18:09 UTC, prabh1601 commented on tle/util/cache_system2.py
>              ranklist = Ranklist(contest, problems, standings, now, is_rated=is_rated)
Yes, this is intended in the change.

The previous code did rank list calculations either with predict_changes or fetch_changes as true. However, this model fails to work in a few cases. Recent/Ongoing contests were fetched from ranklistcache rather than an API call in the previous code version. 

The new version works as follows: In order to fetch the official rank list (with +official), the cache is not used, rather we make an API call, which will, in turn, won't return rating changes(it's a recent/ongoing contest). This iteration of code helps to fallback to predict_changes in case fetching rating changes fails (is_rated being false and in turn returning none as a rank list).

This would also result in showing predicted deltas in the case of old unrated contests as a side benefit.

2023-05-01 18:09 UTC, prabh1601 commented on tle/util/cache_system2.py
> +        if not show_unofficial and 'Educational' in ranklist.contest.name:
I think it should be `and`. This line aims to remove unofficial people when the official educational contest rank list also returns div1s, which has the following conditions
1. We passed +official flag to command -> not show_unofficial
2. It was an Educational Contest

2023-05-01 18:09 UTC, prabh1601 commented on tle/util/ranklist/ranklist.py
> +    def fix_rated_standings(self):
Oh very true, I agree this is a much better choice for the naming conventions.

2023-05-01 18:09 UTC, prabh1601 commented on tle/util/ranklist/ranklist.py
> +            id_ = row.party.teamName or row.party.members[0].handle
This will solve #72, currently, the rank list uses teamID (which is an integer - [API Docs](https://codeforces.com/apiHelp/objects#Party)) to store the non-ghost teams. This leads to the fact that a lookup cant be performed based on the team name. We can exclusively use team names for teams other than Ghosts as well

With this change, now the lookup is based on 
1. team-name in case of a team 
2. first team member's handle in case it's not a team (in which case the team name would be None)

2023-05-01 18:10 UTC, prabh1601 commented on tle/util/ranklist/ranklist.py
> +        fixed_standings = []
Agreed. Much better convention

2023-05-01 18:11 UTC, prabh1601 commented on tle/util/ranklist/ranklist.py
> +            handle = contestant.party.teamName or contestant.party.members[0].handle
I agree, will make life a lot easier.

2023-05-02 21:56 UTC, algmyr commented on tle/util/ranklist/ranklist.py
> +            id_ = row.party.teamName or row.party.members[0].handle
Gotcha

2023-05-02 21:58 UTC, algmyr approved these changes
Cool, thanks for the PR!

2023-05-02 21:58 UTC, merged