Add a way to install files using Pip
cheran-senthil/TLE pull request #519
Opened 2024-01-20 06:15 UTC by E-M-Bailey

fixes #518 

This adds a new run script, run-pip.sh, which uses Pip instead of Poetry to install dependencies. It also modifies the README with appropriate instructions.

2024-01-22 23:04 UTC, algmyr requested changes
Hi, sorry for not getting to this for a bit. Added a comment about making the venv usage (which I like) common among the script and configurable. Should be a pretty minor change, I hope you don't mind. :)

2024-01-22 23:04 UTC, algmyr commented on run-pip.sh
> +. .venv/bin/activate
WDYT about making this flexible wrt venv usage? So, add something like this to `environment.template`
```
# Set to enable automatic venv usage.
export VENV_DIR=""
```
and then
```suggestion
if [[ -n "${VENV_DIR}" ]]; then
    python3 -m venv "${VENV_DIR}"
    . "${VENV_DIR}/bin/activate"
fi
```
adding the same to the regular startup script might also be a nice idea.

And of course, then document this feature in some sensible place in the readme.

2024-01-26 22:39 UTC, algmyr commented
I guess I could make that change myself in a follow-up.

2024-01-26 22:39 UTC, algmyr commented on run-pip.sh
> +. .venv/bin/activate
Follow-up...

2024-01-26 22:40 UTC, merged

2024-01-26 22:42 UTC, E-M-Bailey commented
Sorry, I missed your original response. I'm happy to try making the changes myself sometime this weekend, although I don't have a good way of testing the non-Pip version.

2024-01-26 23:11 UTC, algmyr commented
> Sorry, I missed your original response. I'm happy to try making the changes myself sometime this weekend, although I don't have a good way of testing the non-Pip version.

No worries, I made the changes already in #520. You'll have to make a change to add an environment variable but that should be about it. :)